import numpy as np
import matplotlib.pyplot as plt
eta, rho, v0, order, binder, suscep = np.loadtxt('overall_metrics.txt', delimiter=',', unpack=True)
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
img = ax.scatter(eta, rho, v0, c=order, cmap='plasma')
fig.colorbar(img)
plt.xlabel("Noise")
plt.ylabel("Density")
ax.set_zlabel('Speed')
plt.title("Average Order Parameter Distribution")
plt.savefig("orderDist.png")
plt.close()

fig = plt.figure()
ax = fig.add_subplot(projection='3d')
img = ax.scatter(eta, rho, v0, c=binder, cmap='plasma')
fig.colorbar(img)
plt.xlabel("Noise")
plt.ylabel("Density")
ax.set_zlabel('Speed')
plt.title("Average Binder Cumulant Distribution")
plt.savefig("binderDist.png")

fig = plt.figure()
ax = fig.add_subplot(projection='3d')
img = ax.scatter(eta, rho, v0, c=binder, cmap='plasma')
fig.colorbar(img)
plt.xlabel("Noise")
plt.ylabel("Density")
ax.set_zlabel('Speed')
plt.title("Average Binder Cumulant Distribution")
plt.savefig("binderDist.png")

fig = plt.figure()
ax = fig.add_subplot(projection='3d')
img = ax.scatter(eta, rho, v0, c=suscep, cmap='plasma')
fig.colorbar(img)
plt.xlabel("Noise")
plt.ylabel("Density")
ax.set_zlabel('Speed')
plt.title("Average Susceptibility Distribution")
plt.savefig("suscepDist.png")